In [1]:
pv = 100
f = 1.03
n = 2

In [2]:
fv = pv * f**n
fv

106.08999999999999

In [3]:
import math

In [4]:
fv = pv*math.pow(f,n)
fv

106.08999999999999

In [5]:
math.sqrt(fv/pv) - 1

0.030000000000000027

In [6]:
math.sin(3)

0.1411200080598672

In [7]:
math.e

2.718281828459045

In [8]:
math.pi

3.141592653589793

In [10]:
import math as ma

In [11]:
ma.pi

3.141592653589793

In [12]:
from math import sqrt as sq

In [13]:
sq(fv/pv) - 1

0.030000000000000027

# the numpy package

In [14]:
import numpy as np

In [15]:
np.sqrt(fv/pv)

1.03

In [16]:
pv * np.power(f,n)

106.08999999999999

# Numpy arrays

In [17]:
import numpy as np

In [18]:
cf = [50, 100, 120, 150, 200, 300]
cf

[50, 100, 120, 150, 200, 300]

In [19]:
cf_a = np.array(cf)
cf_a

array([ 50, 100, 120, 150, 200, 300])

In [20]:
type(cf_a)

numpy.ndarray

In [21]:
cf_new = []
for i in cf:
    cf_new.append(i-20)
cf_new

[30, 80, 100, 130, 180, 280]

In [22]:
cf_a-20

array([ 30,  80, 100, 130, 180, 280])

In [23]:
cf_a

array([ 50, 100, 120, 150, 200, 300])

In [24]:
add_cf = np.array([10,20,-10,30,10,-5])
add_cf

array([ 10,  20, -10,  30,  10,  -5])

In [25]:
cf_a + add_cf

array([ 60, 120, 110, 180, 210, 295])

In [26]:
cf_a.dtype

dtype('int32')

In [27]:
l = [100, 20.5, 30, 10.7, True, "Apple"]
l

[100, 20.5, 30, 10.7, True, 'Apple']

In [28]:
a = np.array(l)
a

array(['100', '20.5', '30', '10.7', 'True', 'Apple'], dtype='<U32')

In [29]:
for element in a:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Indexing and slicing numpy arrays

In [30]:
import numpy as np

In [31]:
cf = np.array([50, 100, 120, 150, 200, 300])

In [32]:
cf[0]

50

In [33]:
cf[2:4]

array([120, 150])

In [35]:
cf[:3]

array([ 50, 100, 120])

In [36]:
cf[1:5:2]

array([100, 150])

In [37]:
cf[::-1]

array([300, 200, 150, 120, 100,  50])

# Vectorized operations with numpy

In [38]:
import numpy as np

In [39]:
cf = np.array([50, 100, 120, 150, 200, 300])
cf

array([ 50, 100, 120, 150, 200, 300])

In [40]:
cf*1.1

array([ 55., 110., 132., 165., 220., 330.])

In [41]:
cf+20

array([ 70, 120, 140, 170, 220, 320])

In [43]:
cf_add = np.array([10, 20, 5, -10, 20, 10])
cf_add

array([ 10,  20,   5, -10,  20,  10])

In [44]:
cf + cf_add

array([ 60, 120, 125, 140, 220, 310])

In [45]:
cf = np.array([-200, 20, 50, 70, 100, 50])
r = 0.06
f = 1 + r

In [46]:
n = np.array([0,1,2,3,4,5])

In [47]:
cf / f**n

array([-200.        ,   18.86792453,   44.499822  ,   58.77334981,
         79.20936632,   37.36290864])

In [49]:
pv_array = cf / f**n
pv_array

array([-200.        ,   18.86792453,   44.499822  ,   58.77334981,
         79.20936632,   37.36290864])

In [50]:
NPV = pv_array.sum()
NPV

38.71337130837991

In [53]:
NPV = 0
for i in range(len(cf)):
    NPV += cf[i]/f**i
print(NPV)

38.71337130837991


# Changing Elements in Numpy Arrays & Mutability

In [54]:
import numpy as np

In [55]:
cf = np.array([100, 10,20,50,30,25])

In [56]:
cf[0] = 95

In [57]:
cf

array([95, 10, 20, 50, 30, 25])

In [58]:
cf[1:]

array([10, 20, 50, 30, 25])

In [59]:
cf

array([95, 10, 20, 50, 30, 25])

In [60]:
cf[1:] = 45

In [61]:
cf

array([95, 45, 45, 45, 45, 45])

In [62]:
cf+20

array([115,  65,  65,  65,  65,  65])

In [63]:
cf

array([95, 45, 45, 45, 45, 45])

In [64]:
cf += 20

In [65]:
cf

array([115,  65,  65,  65,  65,  65])

In [66]:
cf1 = np.array([100, 10, 20, 50, 30, 25])
cf1

array([100,  10,  20,  50,  30,  25])

In [67]:
cf2 = cf1[:]

In [68]:
cf2

array([100,  10,  20,  50,  30,  25])

In [70]:
cf1[0] = 90
cf1

array([90, 10, 20, 50, 30, 25])

In [71]:
cf2

array([90, 10, 20, 50, 30, 25])

In [72]:
a = [1,2,3]
b = a[:]
b

[1, 2, 3]

In [73]:
a[0] = 2
a

[2, 2, 3]

In [74]:
b

[1, 2, 3]

In [75]:
cf1 = np.array([1,2,3,4,5])
cf1

array([1, 2, 3, 4, 5])

In [77]:
cf2 = cf1.copy()

In [78]:
cf2

array([1, 2, 3, 4, 5])

In [79]:
cf1[0] = 2
cf1

array([2, 2, 3, 4, 5])

In [80]:
cf2

array([1, 2, 3, 4, 5])

# view vs copy

In [1]:
import numpy as np

In [2]:
cf = np.array([0,1,2,3,4,5])
cf

array([0, 1, 2, 3, 4, 5])

In [4]:
last_3 = cf[-3:]
last_3

array([3, 4, 5])

In [5]:
last_3[0] = 5

In [6]:
last_3

array([5, 4, 5])

In [7]:
cf

array([0, 1, 2, 5, 4, 5])